apiVersion: v1
kind: Service
metadata:
  name: mysvc2
  namespace: cdts
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
